#!/bin/sh

var=0
while :
do
  mousePosition=$(wmp)
  mousePositionArray=(`echo $mousePosition | tr ' ' '\n'`)
  x=$((((mousePositionArray[0]))/40*40-1))
  y=$((((mousePositionArray[1]))/40*40-1))

  $(wrs -a $x $y $(pfw))
  var=$((var+1))
  sleep 0.01
  if (( var > 150 ))
  then
    exit 1
  fi
done
