#!/bin/sh

duratrion=4


text=$@
width=$((${#text} * 10))
echo $width

ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)
barx=$((SW-width-50))
bary=50
barw=200
barh=100

bg=$(xrdb -query | grep background | awk '{print $NF}')
fg=$(xrdb -query | grep foreground | awk '{print $NF}')

baropt="-d -g ${width}x${barh}+${barx}+${bary} -B${bg} -F${fg}"

(echo "%{c} $@"; sleep ${duratrion}) | lemonbar ${baropt}
