#!/bin/bash

list() {
  echo "$(ls ~/usr/dotfiles/themes)"
    exit 1
}

get_xrdb_resource(){
  var=$(xrdb -query | grep "$1" | sed -r "s/^[^:]*?\://")
  echo $var
}

# exit if no argument given
test -z "$1" && list

xrdb -override ~/usr/dotfiles/themes/$1

pkill compton
pkill conky

bg=$(get_xrdb_resource "background")
fg=$(get_xrdb_resource "foreground")
border_w=$(get_xrdb_resource "Window.border")
border_active=$(get_xrdb_resource "Window.active")
border_inactive=$(get_xrdb_resource "Window.inactive")
conky_clock=$(get_xrdb_resource "Conky.clock")
conky_clock_color=$(get_xrdb_resource "Conky.color")
to_exec=$(get_xrdb_resource "exec")
background=$(get_xrdb_resource "bg.picture")
background_setting=$(get_xrdb_resource "bg.setting")

hsetroot $background_setting $background

if [ -n "$conky_clock_color" ]; then
  sed -i -e "s/default_color='#......'/default_color='#$conky_clock_color'/g" ~/.conky/.conkyrc
fi

if [ -n "$conky_clock" ]; then
  sed -i -e "s/\${font\ [^}]*}/$\{font\ $conky_clock\}/g" ~/.conkyrc
fi

if [ -n "$border_w" ]; then
  sed -i -e "s/BW\:\-./BW\:\-$border_w/g" ~/bin/focus.sh
fi

if [ -n "$border_active" ]; then
sed -i -e "s/ACTIVE\:\-0x....../ACTIVE\:\-0x$border_active/g" ~/bin/focus.sh
fi

if [ -n "$border_inactive" ]; then
sed -i -e "s/INACTIVE\:\-0x....../INACTIVE\:\-0x$border_inactive/g" ~/bin/focus.sh
fi

if [ -n "$to_exec" ]; then
  echo $to_exec
  eval "$to_exec"
fi

printf "\033]10;$fg\007"
printf "\033]11;$bg\007"
printf "\033]708;$bg\007"
